#ifndef InitConditionsTypes_AC_H
#define InitConditionsTypes_AC_H
namespace PBM_AC {

enum InitCondition{
  PHASE_FIELD_INIT_UNDEFINED,
  PHASE_FIELD_INIT_VERTICAL,
  PHASE_FIELD_INIT_SPHERE,
  PHASE_FIELD_INIT_SQUARE,
  PHASE_FIELD_INIT_DATA,
  PHASE_FIELD_INIT_2SPHERE,
  PHASE_FIELD_INIT_TAYLOR,
  PHASE_FIELD_INIT_SHRF_VORTEX,
  PHASE_FIELD_INIT_MIXTURE
};

}

#endif