#ifndef InitConditionsTypes_NS_2AC_C_H
#define InitConditionsTypes_NS_2AC_C_H
namespace PB_NS{
enum InitCondition {
    PHASE_FIELD_INIT_UNDEFINED,
    PHASE_FIELD_INIT_VERTICAL,
    PHASE_FIELD_INIT_SPHERE,
    PHASE_FIELD_INIT_CYLINDER,
    PHASE_FIELD_INIT_SQUARE,
    PHASE_FIELD_INIT_DATA,
    PHASE_FIELD_INIT_2SPHERE,
    PHASE_FIELD_INIT_TAYLOR,
    TWO_PLANE,
    BUBBLE_TAYLOR,
    THREEPHASES_SPLASHING_DROPLETS,
    THREEPHASES_RISING_DROPLETS,
    THREEPHASES_RAYLEIGH_TAYLOR,
    THREEPHASES_SPINODAL_DECOMPOSITION,
    THREEPHASES_SPREADING_LENS,
    PHASE_FIELD_INIT_SHRF_VORTEX,
    THREEPHASES_CONTAINER,
    THREEPHASES_CAPSULE
};

}

#endif