#ifndef InitConditionsTypes_NS_AC_C_H
#define InitConditionsTypes_NS_AC_C_H
namespace PBM_NS_AC_Compo {

enum InitCondition {
    PHASE_FIELD_INIT_UNDEFINED,
    PHASE_FIELD_INIT_VERTICAL,
    PHASE_FIELD_INIT_SPHERE,
    PHASE_FIELD_INIT_CYLINDER,
    PHASE_FIELD_INIT_SQUARE,
    PHASE_FIELD_INIT_DATA,
    PHASE_FIELD_INIT_2SPHERE,
    PHASE_FIELD_INIT_TAYLOR,
    TWO_PHASE_SERPENTINE,
    TWO_PHASE_ZALESAK,
    RISING_BUBBLE,
    TWO_PHASE_SPLASH,
    TWO_PHASE_BREAKING_WAVE,
    TWO_PHASE_SPINODAL_DECOMP,
    PHASE_FIELD_INIT_TAYLOR_PERTURB_EXPO,
    PHASE_FIELD_GLASS,
    PHASE_FIELD_TORRICELLI,
    SOLID_INIT_NO_SOLID,
    SOLID_INIT_SPHERE,
    SOLID_INIT_CYLINDER,
    SOLID_INIT_CYLINDER_TANK,
    SOLID_INIT_RECTANGLE,
    SOLID_INIT_GLASS,
    SOLID_INIT_GLASS_HOLE,
    SOLID_INIT_TORRICELLI,
    SOLID_NO_MOVE,
    SOLID_MOVE_OSCILL,
    SOLID_MOVE_ROTATE,
    TWO_PLANE,
    BUBBLE_TAYLOR,
    DAM_BREAK,
    PHASE_FIELD_INIT_MIXTURE
};

}

#endif