#ifndef InitConditionsTypes_GPMIXT_TERNARY_H
#define InitConditionsTypes_GPMIXT_TERNARY_H
namespace PBM_GP_MIXT_TERNARY {

enum InitCondition{
  PHASE_FIELD_INIT_UNDEFINED,
  PHASE_FIELD_INIT_VERTICAL,
  PHASE_FIELD_INIT_SPHERE,
  PHASE_FIELD_INIT_2SPHERE,
  PHASE_FIELD_INIT_SQUARE,
  PHASE_FIELD_INIT_DATA,
  PHASE_FIELD_RANDOM_TERNARY_GLASS,
  PHASE_FIELD_RANDOM_TERNARY_GLASS_SPHERE,
  PHASE_FIELD_RANDOM_VERTICAL_PERTURBED,
  PHASE_FIELD_RANDOM_VERTICAL_PERTURBED_RANDOM,
  PHASE_FIELD_RANDOM_VERTICAL_ERFC_1INT,
  PHASE_FIELD_RANDOM_VERTICAL,ERFC_3INT,
  PHASE_FIELD_RANDOM_TERNARY_PERCO,
  PHASE_FIELD_INIT_VERTICAL_ERFC_1INT,
  PHASE_FIELD_INIT_TERNARY_PERCO,
  PHASE_FIELD_INIT_MIXTURE,
  PHASE_FIELD_INIT_VERTICAL_PERTURBED,
  PHASE_FIELD_INIT_VERTICAL_PERTURBED_RANDOM,
  PHASE_FIELD_INIT_VERTICAL_ERFC_3INT
};

}

#endif