#ifndef InitConditionsTypes_NS_2AC_C_3D_H
#define InitConditionsTypes_NS_2AC_C_3D_H
namespace PBM_NS_2AC_Compo3D{

enum InitCondition {
    PHASE_FIELD_INIT_UNDEFINED,
    PHASE_FIELD_INIT_VERTICAL,
    PHASE_FIELD_INIT_VERTICAL_3_PHASES,
    PHASE_FIELD_INIT_SPHERE,
    PHASE_FIELD_INIT_CYLINDER,
    PHASE_FIELD_INIT_SQUARE,
    PHASE_FIELD_INIT_DATA,
    PHASE_FIELD_INIT_2SPHERE,
    PHASE_FIELD_INIT_TAYLOR,
    PHASE_FIELD_INIT_TAYLOR_3D,
    TWO_PLANE,
    BUBBLE_TAYLOR,
    THREEPHASES_SPLASHING_DROPLETS,
    THREEPHASES_RISING_DROPLETS,
    THREEPHASES_RISING_DROPLETS_3D,
    THREEPHASES_RAYLEIGH_TAYLOR,
    THREEPHASES_RAYLEIGH_TAYLOR_3D,
    SPLASH,
    THREEPHASES_SPINODAL_DECOMPOSITION,
    THREEPHASES_SPREADING_LENS,
    PHASE_FIELD_INIT_SHRF_VORTEX,
    THREEPHASES_CONTAINER,
    THREEPHASES_CAPSULE,
    PHASE_FIELD_INIT_MIXTURE
};
}

#endif