#ifndef InitConditionsTypes_GPMIXT_H
#define InitConditionsTypes_GPMIXT_H
namespace PBM_GP_MIXT {

enum InitCondition{
  PHASE_FIELD_INIT_UNDEFINED,
  PHASE_FIELD_INIT_VERTICAL,
  PHASE_FIELD_INIT_SPHERE,
  PHASE_FIELD_INIT_2SPHERE,
  PHASE_FIELD_INIT_SQUARE,
  PHASE_FIELD_INIT_DATA,
  PHASE_FIELD_INIT_MIXTURE
};

}

#endif