#ifndef InitConditionsTypes_GPMU_TERNARY__H
#define InitConditionsTypes_GPMU_TERNARY__H
namespace PBM_GP_MU_TERNARY{

enum InitCondition{
  PHASE_FIELD_INIT_UNDEFINED,
  PHASE_FIELD_INIT_VERTICAL,
  PHASE_FIELD_INIT_SPHERE,
  PHASE_FIELD_INIT_2SPHERE,
  PHASE_FIELD_INIT_SQUARE,
  PHASE_FIELD_INIT_DATA,
  PHASE_FIELD_RANDOM_TERNARY_GLASS,
  PHASE_FIELD_RANDOM_TERNARY_GLASS_SPHERE
};

}

#endif